fix sglang e2e_sppo test (#1832)
### Checklist Before Starting

- [done] Search for similar PR(s).

### What does this PR do?

Fix error in e2e_sppo  CI test

Exception: sgl-kernel is installed with version 0.0.9.post2, which is
less than the minimum required version 0.1.1. Please reinstall the
latest version with `pip install sgl-kernel --force-reinstall`

For example:

https://github.com/volcengine/verl/actions/runs/15431843178/job/43430980736?pr=1769